version: '3.4'
services:
  krakend_ce:
    # The :watch image restarts the service automatically when the configuration files change.
    # Do not use this image in production, it's meant to speed up your testing and development.
    image: devopsfaith/krakend:2.2.1
    volumes:
      - ./config/krakend:/etc/krakend
      - ./krakend-server-example.so:/etc/krakend/krakend-server-example.so
    ports:
      - "1234:1234"
      - "8080:8080"
      - "8090:8090"
    command: ["run", "-d", "-c", "/etc/krakend/krakend.json"]
